version: 2
jobs:
    build:
        docker:
           - image: circleci/python:3.6.2-stretch-browsers
        steps:
            - checkout
            - run:
                command: |
                    virtualenv -p python3 env
                    . env/bin/activate
                    pip install -r requirements.txt
    test:
        steps:
            - checkout
            - run:
                command: |
                    . ./bin/test.sh

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
