#
# CircleCI v2
#
# Documentation:
# https://circleci.com/docs/2.0/configuration-reference/
#
version: 2

# This defines a list of jobs
# that will be executed after.
jobs:

    # Define a job called 'build'.
    build:

        # This job runs in a docker container.
        docker:
            # Run in an Ubuntu environment.
            - image: tiangolo/uwsgi-nginx-flask
              # These are the list of environment
              # variables that will be passed
              # to the application test.
              environment:
                PYTEST: true
                DEBUG: true
                TERM: xterm

        # In which directory
        # to run the steps?
        working_directory: ~/app-circleci-tests

        # These are the list of steps
        # to be performaned for this job.
        steps:

            # Checkout source code.
            - checkout

            # Update environment.
            - run:
                name: "Update Operating System."
                command: |
                    apt-get update -y

            # Install dependencies.
            - run:
                name: "Install Operating System  dependencies."
                command: |
                    apt-get install -y python3-pip python3 python3-virtualenv python-flake8 python3-flake8 python3-venv git 

            # Restore from cache.
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "requirements.txt" }}

            # Create virtual environment.
            - run:
                name: "Install Python virtual environment."
                command: |
                    python3 -m venv .env
                    . .env/bin/activate
                    pip install --upgrade pip
                    pip install -r ./requirements.txt

            # Save the virtualenv into
            # cache so that we don't install
            # dependencies more than once.
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                    - ".env"

            # Run your tests using pytest.
            - run:
                name: "Run unit tests."
                command: |
                    ./bin/test.sh

            # Run flake8.
            - run:
                name: "Run flake8 tests."
                command: |
                    ./bin/flake8.sh


# Do the deployment
# if all the tests
# are PASSED.
deployment:
    production: # just a label; label names are completely up to you
        branch: master
        commands:
            - ls ./bin/deploy.sh && ./bin/deploy.sh PROD
    development: # just a label; label names are completely up to you
        branch: dev
        commands:
            - ls ./bin/deploy.sh && ./bin/deploy.sh DEV
