#
# CircleCI v2
#
# Documentation:
# https://circleci.com/docs/2.0/configuration-reference/
#
version: 2

# This defines a list of jobs
# that will be executed after.
jobs:

    # Define a job called 'build'.
    build:

        # This job runs in a docker container.
        docker:
            # Run in an Ubuntu environment.
            - image: tiangolo/uwsgi-nginx-flask
              # These are the list of environment
              # variables that will be passed
              # to the application test.
              environment:
                PYTEST: true
                DEBUG: true
                TERM: xterm

        # In which directory
        # to run the steps?
        working_directory: ~/app-circleci-tests

        # Only in master branch
        # and develop branch
        # and hotfix-*
        # and develop-*.
        branches:
            only:
                - master 
                - develop
                - develop-*
                - hotfix-*

        # These are the list of steps
        # to be performaned for this job.
        steps:

            # Create a virtual environment.
            - checkout

            # Update environment.
            - run:
                name: "Update Operating System."
                command: |
                    apt-get update -y

            # Install dependencies.
            - run:
                name: "Install Operating System  dependencies."
                command: |
                    apt-get install -y python3-pip python3 python3-virtualenv python-flake8 python3-flake8 python3-venv git 

            # Restore from cache.
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "requirements.txt" }}

            # Create virtual environment.
            - run:
                name: "Install Python virtual environment."
                command: |
                    python3 -m venv .env
                    . .env/bin/activate
                    pip install --upgrade pip
                    pip install -r ./requirements.txt

            # Save the virtualenv into
            # cache so that we don't install
            # dependencies more than once.
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                    - ".env"

            # Run your tests using pytest.
            - run:
                name: "Run unit tests."
                command: |
                    ./bin/test.sh

            # Run flake8.
            - run:
                name: "Run flake8 tests."
                command: |
                    ./bin/flake8.sh

    # Define a job called 'deploy_to_prod'.
    deploy-to-prod:

        # Deploy using this image.
        docker:
            # Run in an Ubuntu environment.
            - image: ubuntu:16.04

        # In which directory
        # to run the steps?
        working_directory: ~/app-circleci-tests

        # Only in master branch.
        branches:
            only:
                - master 

        # Do the deployment.
        steps:
            - run:
                name: "Deploy if tests pass and branch is master."
                command: ls -la

    # Define a job called 'deploy_to_dev'.
    deploy-to-dev:

        # Deploy using this image.
        docker:
            # Run in an Ubuntu environment.
            - image: ubuntu:16.04

        # In which directory
        # to run the steps?
        working_directory: ~/app-circleci-tests

        # Only in develop branch.
        branches:
            only:
                - develop

        # Do the deployment.
        steps:
            - run:
                name: "Deploy if tests pass and branch is develop."
                command: ls -la

# Do the deployment
# if all the tests
# are PASSED.
deployment:
    production: # just a label; label names are completely up to you
        branch: master
        commands:
            - ./bin/deploy.sh PROD
    dev: # just a label; label names are completely up to you
        branch: develop
        commands:
            - ./bin/deploy.sh PROD
